apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # The maximum number of pods that can be created over the desired number of pods.
      maxSurge: 1 # ensures that we do not have more than 3 pods at any given time.
      maxUnavailable: 50% # The maximum number of pods that can be unavailable during the update.
  selector:
    matchLabels:
      app.kubernetes.io/instance: grade-submission-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission 
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      containers:
        - name: grade-submission-api
          image: rslim087/kubernetes-course-grade-submission-api:stateless
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 3000