apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
# The data field is where we put the key-value pairs that we want to store in the secret.
# k8s expect the values here to be base64 encoded values. If you want to store the secret 
# plain text, you'd need to use `stringData` instead of `data`.

# You can convert plain text to base64 by using the following command:
# `echo -n "admin" | base64`
stringData:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}
