apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  # ClusterIP Service: the default type for services
  # Used for internal pod-to-pod communication within the cluster.
  selector:
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  ports:
  - port: {{ .Values.workload.port }}
    targetPort: {{ .Values.workload.port }}
