microservice: # general service detail
  name: grade-submission-api
  namespace: grade-submission
  replicas: 2

workload: # container specific configuration
  image: "rslim087/kubernetes-course-grade-submission-api:stateless-v3"
  port: 3000
  livenessDelay: 15
  resources:
    memory: "128Mi"
    cpu: "128m"

env: # environment variables
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"

secrets: # sensitive data
  MONGODB_USER: "YWRtaW4="
  MONGODB_PASSWORD: "YWRtaW4yMDAz"