microservice: # general service detail
  name: grade-submission-api
  namespace: grade-submission
  replicas: 2

workload: # container specific configuration
  image: "rslim087/kubernetes-course-grade-submission-api:stateless-v4"
  port: 3000
  livenessDelay: 15
  resources:
    memory: "128Mi"
    cpu: "128m"

secrets: # sensitive data
  MONGODB_URI: "mongodb://mongodb.mongodb.svc.cluster.local:27017"