apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  # The clusterIP is an automatically load balancer when you have multiple pod replicas.
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  ports:
  - port: {{ .Values.workload.port }}
    targetPort: {{ .Values.workload.port }}
